# Generated by Django 5.0.3 on 2024-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceptar_oferta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Desaprobado', 'Desaprobado'), ('Pendiente', 'Pendiente'), ('Actualización de documentos necesaria', 'Actualización de documentos necesaria')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
