# Generated by Django 4.2.13 on 2024-05-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceptar_oferta', '0004_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='estado',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('noAceptado', 'No Aceptado')], default='noAceptado', max_length=20),
        ),
    ]
